# Generated by Django 5.1.15 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='advisor_enabled',
            field=models.BooleanField(default=False, help_text='Allow this user to see the in-game advisor hints.'),
        ),
    ]
