# Generated by Django 6.0.2 on 2026-02-24 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=4)),
                ('current_player_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_in_bank', models.JSONField(default=dict)),
                ('visible_cards', models.JSONField(default=dict)),
                ('decks', models.JSONField(default=dict)),
                ('available_nobles', models.JSONField(default=list)),
                ('last_round_triggered_by', models.IntegerField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('tokens', models.JSONField(default=dict)),
                ('purchased_card_ids', models.JSONField(default=list)),
                ('reserved_card_ids', models.JSONField(default=list)),
                ('noble_ids', models.JSONField(default=list)),
                ('prestige_points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'order'), ('game', 'user')},
            },
        ),
    ]
