# Generated by Django 6.0.2 on 2026-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_last_survey_at_game_left_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('bonus', models.CharField(choices=[('white', 'White (Diamond)'), ('blue', 'Blue (Sapphire)'), ('green', 'Green (Emerald)'), ('red', 'Red (Ruby)'), ('black', 'Black (Onyx)')], max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('cost_white', models.IntegerField(default=0)),
                ('cost_blue', models.IntegerField(default=0)),
                ('cost_green', models.IntegerField(default=0)),
                ('cost_red', models.IntegerField(default=0)),
                ('cost_black', models.IntegerField(default=0)),
                ('background_image', models.URLField(blank=True, help_text='URL for card background image', max_length=500, null=True)),
            ],
            options={
                'ordering': ['level', 'bonus', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Noble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=3)),
                ('req_white', models.IntegerField(default=0)),
                ('req_blue', models.IntegerField(default=0)),
                ('req_green', models.IntegerField(default=0)),
                ('req_red', models.IntegerField(default=0)),
                ('req_black', models.IntegerField(default=0)),
                ('background_image', models.URLField(blank=True, help_text='URL for noble background image', max_length=500, null=True)),
                ('name', models.CharField(blank=True, help_text='Optional noble name', max_length=100)),
            ],
        ),
    ]
