# Generated by Django 6.0.2 on 2026-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_seed_cards_and_nobles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentcard',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Card background image', null=True, upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='noble',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Noble background image', null=True, upload_to='nobles/'),
        ),
    ]
