# Generated by Django 5.1.15 on 2026-02-28 06:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentcard',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='noble',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
