# Generated by Django 5.1.15 on 2026-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_developmentcard_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='pending_action_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
