# Generated by Django 5.1.15 on 2026-03-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_pending_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('round_number', models.IntegerField()),
                ('action_type', models.CharField(choices=[('take_tokens', 'Take Tokens'), ('reserve_card', 'Reserve Card'), ('buy_card', 'Buy Card'), ('noble_visit', 'Noble Visit')], max_length=20)),
                ('action_data', models.JSONField(default=dict)),
                ('prestige_points_after', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gameplayer')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
    ]
