# Generated by Django 5.1.15 on 2026-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
