# Generated by Django 6.0.2 on 2026-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_turn_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
