# Generated by Django 5.1.15 on 2026-03-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_add_timer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='balancing_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Override global balancing. None=use global setting, True=force on, False=force off.', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='balancing_level',
            field=models.CharField(blank=True, default='', help_text="Override balancing level: '' (use global), 'off', 'soft', 'strict'.", max_length=10),
        ),
    ]
