# Generated by Django 5.1.15 on 2026-03-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_add_balancing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='balancing_enabled',
        ),
        migrations.RemoveField(
            model_name='game',
            name='balancing_level',
        ),
    ]
