# Generated by Django 6.0.3 on 2026-03-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_advisor_config'),
        ('game', '0013_remove_balancing_fields'),
    ]

    operations = [
    ]
