# Generated by Django 6.0.2 on 2026-02-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='p1_rating_before',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2_rating_before',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rating_change_p1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rating_change_p2',
        ),
        migrations.AddField(
            model_name='match',
            name='player_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='player_count_preference',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('rating_before', models.IntegerField(default=0)),
                ('rating_change', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='competitive.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='competitive.player')),
            ],
            options={
                'ordering': ['placement'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
